### ISSUE TITLE
Swagger UI - Request URL is always "null"

### ISSUE THREAD

**Issue by metasection** [z0mt3c/node-restify-swagger#9]
Working great so far.  Great project thank you.  

Minor problem:  the "Request URL" field is always "null".  

I would expect this field to display something like "http://localhost:8001/get/..." after pressing the "Try it out" button.

![screen shot 2014-09-28 at 8 52 22 am](https://cloud.githubusercontent.com/assets/4357688/4434278/6aa56cc0-470e-11e4-873a-3a81565dd693.png)

**Comment by pdurkim** [comment]
so, the reason request URL is always null is because there's no base path?
